import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <nav className="bg-sky-950 text-white p-5 h-24 flex items-center justify-between">
          <Link href="/">My App</Link>
          <ul>
            <li>
              <Link href="/login"> Login</Link>
            </li>
            <li>
              <Link href="/register"> Register</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
